Feature: Add `StyleSheet`
contember/interface pull request #393
Opened 2022-08-02 09:18 UTC by attitude

Allows to extend & resolve `className` of component and its sub-components.

2022-08-18 12:52 UTC, JanTvrdik requested changes
> Reviewed 2 of 23 files at r1, 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/393)* status: 3 of 23 files reviewed, 15 unresolved discussions (waiting on @attitude)

___
*[`packages/ui/src/components/StyleSheet/extendStyleSheet.ts` line 11 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kthvd8_3uJpVtdDRu:-N9kthvd8_3uJpVtdDRv:b-j9256v) ([raw file](https://github.com/contember/admin/blob/cca338b49b1f87616f387ced656c2ff5becf11ba/packages/ui/src/components/StyleSheet/extendStyleSheet.ts#L11)):*
> ```XML
>   const partial = deepMerge(
>     toStyleSheet(one as any),
>     toStyleSheet(two as any),
> ```

`as any` should not be used



_Code quote:_
```XML
    toStyleSheet(one as any),
    toStyleSheet(two as any),
```
___
*[`packages/ui/src/components/StyleSheet/extendStyleSheet.ts` line 25 at r4](https://reviewable.io/reviews/contember/admin/393#-N9ktWAD6bwEUZ2etKL5:-N9ktWAD6bwEUZ2etKL6:b-ijfoa3) ([raw file](https://github.com/contember/admin/blob/cca338b49b1f87616f387ced656c2ff5becf11ba/packages/ui/src/components/StyleSheet/extendStyleSheet.ts#L25)):*
> ```XML
> }
> 
> export function createStyleSheet<T extends StyleSheetClassName[]>(...styles: T): UnionToIntersection<ToStyleSheet<T[number]>> {
> ```

why do have two functions doing exactly the same? why not have `creatStyleSheet` only?
___
*[`packages/ui/src/components/StyleSheet/Helpers.ts` line 51 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kvYBb2auEbPns-xN8:-N9kvYBb2auEbPns-xN9:bqnbpr2) ([raw file](https://github.com/contember/admin/blob/cca338b49b1f87616f387ced656c2ff5becf11ba/packages/ui/src/components/StyleSheet/Helpers.ts#L51)):*
> ```XML
> const REASONABLE_ARRAY_FLAT_DEPTH = 9
> 
> export function toFlatArrayOfClassNameValues(value: any[]): (string | StyleSheetValueResolver)[] {
> ```

should not be typed as any[]
___
*[`packages/ui/src/components/StyleSheet/Helpers.ts` line 52 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kwUHG3ie-PLGuXNv5:-N9kwUHG3ie-PLGuXNv6:b3k96il) ([raw file](https://github.com/contember/admin/blob/cca338b49b1f87616f387ced656c2ff5becf11ba/packages/ui/src/components/StyleSheet/Helpers.ts#L52)):*
> ```XML
> 
> export function toFlatArrayOfClassNameValues(value: any[]): (string | StyleSheetValueResolver)[] {
>   return excludeFromArray(null, value.flat(REASONABLE_ARRAY_FLAT_DEPTH).map(
> ```

should not support nested arrays
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 4 at r4](https://reviewable.io/reviews/contember/admin/393#-N9k-GAF7Z9P7wj8vq16:-N9k-GAF7Z9P7wj8vq17:undefined) ([raw file](https://github.com/contember/admin/blob/cca338b49b1f87616f387ced656c2ff5becf11ba/packages/ui/src/components/StyleSheet/Types.ts#L4)):*
> ```XML
> export type StyleSheetVariableValue = StyleSheetValueResolver | string | number | boolean | null | undefined
> 
> export type StyleSheetValueResolver = (variables: Record<StyleSheetVariableKey, StyleSheetVariableValue>) => Exclude<StyleSheetVariableValue, StyleSheetValueResolver>
> ```





_Suggestion:_
```XML
export type StyleSheetValueResolver = (variables: Record<StyleSheetVariableKey, Exclude<StyleSheetVariableValue, StyleSheetValueResolver>>) => Exclude<StyleSheetVariableValue, StyleSheetValueResolver>
```
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 6 at r4](https://reviewable.io/reviews/contember/admin/393#-N9k0oP09RmTIz4IfZqn:-N9k0oP09RmTIz4IfZqo:bfl63ff) ([raw file](https://github.com/contember/admin/blob/cca338b49b1f87616f387ced656c2ff5becf11ba/packages/ui/src/components/StyleSheet/Types.ts#L6)):*
> ```XML
> export type StyleSheetValueResolver = (variables: Record<StyleSheetVariableKey, StyleSheetVariableValue>) => Exclude<StyleSheetVariableValue, StyleSheetValueResolver>
> 
> export type ProcessedStyleSheetClassName = undefined | null | (string | StyleSheetValueResolver)[]
> ```

why not allow the same stuff as StyleSheetClassName?
why allow `undefined | null` ?



_Suggestion:_
```XML
export type ProcessedStyleSheetClassName =
  | (string | StyleSheetValueResolver)[]
  | StyleSheetValueResolver
  | string
  | number
  | boolean
  | null
  | undefined
```
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 16 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kxehAA3Yo05cg_3H8:-N9kxehB1srgVdFADGQr:by41t34) ([raw file](https://github.com/contember/admin/blob/cca338b49b1f87616f387ced656c2ff5becf11ba/packages/ui/src/components/StyleSheet/Types.ts#L16)):*
> ```XML
>   | null
>   | undefined
>   | { [Property in string]: (
> ```

this does not seem to work for me at all, the following seems to work

~~~tsx
type AlphaLower = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z'
type AlphaUpper = Uppercase<AlphaLower>
type Alpha = AlphaLower | AlphaUpper

export type StyleSheetVariableKey = `\$${Alpha}${string}`
export type StyleSheetVariableValue = StyleSheetValueResolver | string | number | boolean | null | undefined
export type StyleSheetVariableValueResolved = string | number | boolean | null | undefined

export type StyleSheetValueResolver = (variables: Record<StyleSheetVariableKey, StyleSheetVariableValueResolved>) => StyleSheetVariableValueResolved

export type ProcessedStyleSheetClassName = (string | StyleSheetValueResolver)[]

export type StyleSheetClassNameBase = StyleSheetValueResolver | string | number | boolean | null | undefined
export type StyleSheetClassName =
	| Iterable<StyleSheetClassNameBase>
	| StyleSheetClassNameBase
	| NotArray<{
		[key: `${Alpha}${string}`]: StyleSheetClassName,
		[key: StyleSheetVariableKey]: StyleSheetVariableValue,
		$?: ProcessedStyleSheetClassName
	}>
~~~
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 19 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kaPu-6oklBDrb249q:-N9kaPu-6oklBDrb249r:bvmscjw) ([raw file](https://github.com/contember/admin/blob/cca338b49b1f87616f387ced656c2ff5becf11ba/packages/ui/src/components/StyleSheet/Types.ts#L19)):*
> ```XML
>     Property extends StyleSheetVariableKey
>     ? (Property extends '$'
>       ? ProcessedStyleSheetClassName
> ```

Why is `className={"hello"}` allowed but `className={{ $: "hello" }}` is not?
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 25 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kDFc8Coh3nII8ugta:-N9kDFc8Coh3nII8ugtb:blxwy5a) ([raw file](https://github.com/contember/admin/blob/cca338b49b1f87616f387ced656c2ff5becf11ba/packages/ui/src/components/StyleSheet/Types.ts#L25)):*
> ```XML
>   ) }
> 
> export type ToStyleSheet<T> =
> ```

why not `<T extends StyleSheetClassName>`
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 46 at r4](https://reviewable.io/reviews/contember/admin/393#-N9k3uf73p6Q05UsXgB0:-N9k3uf73p6Q05UsXgB1:bmjz544) ([raw file](https://github.com/contember/admin/blob/cca338b49b1f87616f387ced656c2ff5becf11ba/packages/ui/src/components/StyleSheet/Types.ts#L46)):*
> ```XML
> export type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void ? I : never
> 
> export type ObjectExceptArray = { join?: never, [key: string]: any }
> ```

1) `[key: string]: any` will effectively turn of all type checking
2) you can detect array based Symbol.iterator key



_Suggestion:_
```XML
export type ObjectExceptArray = object & { [Symbol.iterator]?: never }
```
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 52 at r4](https://reviewable.io/reviews/contember/admin/393#-N9k4p7R1s5wRF19Vry7:-N9k4p7R1s5wRF19Vry8:b-d5chh7) ([raw file](https://github.com/contember/admin/blob/cca338b49b1f87616f387ced656c2ff5becf11ba/packages/ui/src/components/StyleSheet/Types.ts#L52)):*
> ```XML
> }
> 
> export type ComponentStyleSheet<T extends ObjectExceptArray = {}> = T | { [key: string]: any }
> ```

` { [key: string]: any }` will effectively turn of all type checking, making the entire type useless
___
*[ [...]

2022-08-19 11:31 UTC, attitude reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/contember/admin/393#-:-N9oyHP6-cocYN42tYx8:b-896fix)* status: 3 of 30 files reviewed, 15 unresolved discussions (waiting on @attitude and @JanTvrdik)

___
*[`packages/ui/src/components/StyleSheet/extendStyleSheet.ts` line 11 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kthvd8_3uJpVtdDRu:-N9oyO-n7WBtVDe8MT_g:b-896fix) ([raw file](https://github.com/contember/admin/blob/5fe0872cbd90b44e81be4fe35ddae7f963d3c421/packages/ui/src/components/StyleSheet/extendStyleSheet.ts#L11)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

`as any` should not be used
</blockquote></details>

Done.
___
*[`packages/ui/src/components/StyleSheet/extendStyleSheet.ts` line 25 at r4](https://reviewable.io/reviews/contember/admin/393#-N9ktWAD6bwEUZ2etKL5:-N9oyc-QAlPEC-21EMKl:b-aq2hqw) ([raw file](https://github.com/contember/admin/blob/5fe0872cbd90b44e81be4fe35ddae7f963d3c421/packages/ui/src/components/StyleSheet/extendStyleSheet.ts#L25)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why do have two functions doing exactly the same? why not have `creatStyleSheet` only?
</blockquote></details>

I was still considering naming. Renamed to `toClassName()`
___
*[`packages/ui/src/components/StyleSheet/Helpers.ts` line 51 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kvYBb2auEbPns-xN8:-N9p7lYr8brWZHJnhda2:b-896fix) ([raw file](https://github.com/contember/admin/blob/5fe0872cbd90b44e81be4fe35ddae7f963d3c421/packages/ui/src/components/StyleSheet/Helpers.ts#L51)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

should not be typed as any[]
</blockquote></details>

Done.
___
*[`packages/ui/src/components/StyleSheet/Helpers.ts` line 52 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kwUHG3ie-PLGuXNv5:-N9ozBZd74gor3Yu8GQK:b-3w2ntw) ([raw file](https://github.com/contember/admin/blob/5fe0872cbd90b44e81be4fe35ddae7f963d3c421/packages/ui/src/components/StyleSheet/Helpers.ts#L52)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

should not support nested arrays
</blockquote></details>

What would be the downside?
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 4 at r4](https://reviewable.io/reviews/contember/admin/393#-N9k-GAF7Z9P7wj8vq16:-N9ozyRE0PavzKhrvygj:b-896fix) ([raw file](https://github.com/contember/admin/blob/5fe0872cbd90b44e81be4fe35ddae7f963d3c421/packages/ui/src/components/StyleSheet/Types.ts#L4)):*
> ```XML
> export type StyleSheetVariableValue = StyleSheetValueResolver | string | number | boolean | null | undefined
> 
> export type StyleSheetValueResolver = (variables: Record<StyleSheetVariableKey, StyleSheetVariableValue>) => Exclude<StyleSheetVariableValue, StyleSheetValueResolver>
> ```

Done.
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 6 at r4](https://reviewable.io/reviews/contember/admin/393#-N9k0oP09RmTIz4IfZqn:-N9p-GzZ1jFHXzI8D1UI:b-2k74el) ([raw file](https://github.com/contember/admin/blob/5fe0872cbd90b44e81be4fe35ddae7f963d3c421/packages/ui/src/components/StyleSheet/Types.ts#L6)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why not allow the same stuff as StyleSheetClassName?
why allow `undefined | null` ?
</blockquote></details>

Done. Changed to `(string | StyleSheetValueResolver)[]` as you did in the comment bellow
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 16 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kxehAA3Yo05cg_3H8:-N9pb-vP3DPIlUBjmTQL:b-896fix) ([raw file](https://github.com/contember/admin/blob/5fe0872cbd90b44e81be4fe35ddae7f963d3c421/packages/ui/src/components/StyleSheet/Types.ts#L16)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

this does not seem to work for me at all, the following seems to work

~~~tsx
type AlphaLower = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z'
type AlphaUpper = Uppercase<AlphaLower>
type Alpha = AlphaLower | AlphaUpper

export type StyleSheetVariableKey = `\$${Alpha}${string}`
export type StyleSheetVariableValue = StyleSheetValueResolver | string | number | boolean | null | undefined
export type StyleSheetVariableValueResolved = string | number | boolean | null | undefined

export type StyleSheetValueResolver = (variables: Record<StyleSheetVariableKey, StyleSheetVariableValueResolved>) => StyleSheetVariableValueResolved

export type ProcessedStyleSheetClassName = (string | StyleSheetValueResolver)[]

export type StyleSheetClassNameBase = StyleSheetValueResolver | string | number | boolean | null | undefined
export type StyleSheetClassName =
	| Iterable<StyleSheetClassNameBase>
	| StyleSheetClassNameBase
	| NotArray<{
		[key: `${Alpha}${string}`]: StyleSheetClassName,
		[key: StyleSheetVariableKey]: StyleSheetVariableValue,
		$?: ProcessedStyleSheetClassName
	}>
~~~
</blockquote></details>

Done.
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 19 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kaPu-6oklBDrb249q:-N9lGQ3K9axD9L4kbDho:b-896fix) ([raw file](https://github.com/contember/admin/blob/5fe0872cbd90b44e81be4fe35ddae7f963d3c421/packages/ui/src/components/StyleSheet/Types.ts#L19)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

Why is `className={"hello"}` allowed but `className={{ $: "hello" }}` is not?
</blockquote></details>

Done.
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 25 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kDFc8Coh3nII8ugta:-N9otRxZ4BDcp0_Btzuc:b-896fix) ([raw file](https://github.com/contember/admin/blob/5fe0872cbd90b44e81be4fe35ddae7f963d3c421/packages/ui/src/components/StyleSheet/Types.ts#L25)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why not `<T extends StyleSheetClassName>`
</blockquote></details>

Done.
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 46 at r4](https://reviewable.io/reviews/contember/admin/393#-N9k3uf73p6Q05UsXgB0:-N9ot_Yn5ZMGR9Wo02jM:b-896fix) ([raw file](https://github.com/contember/admin/blob/5fe0872cbd90b44e81be4fe35ddae7f963d3c421/packages/ui/src/components/StyleSheet/Types.ts#L46)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

1) `[key: string]: any` will effectively turn of all type checking
2) you can detect array based Symbol.iterator key
</blockquote></details>

Done.
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 52 at r4](https://reviewable.io/reviews/contember/admin/393#-N9k4p7R1s5wRF19Vry7:-N9pb-Fa5noXKACiWx6N:b-896fix) ([raw file](https://github.com/contember/admin/blob/5fe0872cbd90b44e81be4fe35ddae7f963d3c421/packages/ui/src/components/StyleSheet/Types.ts#L52)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

` { [key: string]: any }` will effectively turn of all type checking, making the entire type useless
</blockquote></details>

Done.
___
*[`packages/ui/src/components/StyleSheet/toStyleSheet.ts` line 44 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kC0A74o39AcUqaTq8:-N9oti7d15GT-_D8sEO_:bp6091h) ([raw file](https://github.com/contember/admin/blob/5fe0872cbd90b44e81be4fe35ddae7f963d3c421/packages/ui/src/components/StyleSheet/toStyleSheet.ts#L44)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

what is the point of declaring the overriden signature, when you return always `ToStyleSheet<T>` anyway?
</blockquote></details>

I forgot to remove it after consolidation of the return type.

Done.
___
*[`packages/ui/src/components/StyleSheet/toStyleSheet.ts` line 55 at r4](https://reviewable.io/reviews/contember/admin/393#-N9kCz47BBul4Aq7A [...]

2022-08-24 20:14 UTC, JanTvrdik requested changes
> Reviewed 1 of 16 files at r3, 5 of 6 files at r5, 2 of 12 files at r6.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/393)* status: 3 of 32 files reviewed, 22 unresolved discussions (waiting on @attitude and @JanTvrdik)

___
*[`packages/ui/src/components/Forms/FieldContainer/FieldContainer.tsx` line 52 at r6](https://reviewable.io/reviews/contember/admin/393#-NA9aQyq1Z7ky_L1PjwZ:-NA9aQyq1Z7ky_L1Pjw_:b8lex4w) ([raw file](https://github.com/contember/admin/blob/9a85a3d5e8c9a127e5109e5e88f5126f8b6b3fd1/packages/ui/src/components/Forms/FieldContainer/FieldContainer.tsx#L52)):*
> ```XML
> 			$labelPosition: labelPosition,
> 			$width: width,
> 			$error: !!(errors?.length),
> ```

`errors !== undefined && errors.length > 0`
___
*[`packages/ui/src/components/StyleSheet/Helpers.ts` line 51 at r7](https://reviewable.io/reviews/contember/admin/393#-NAF0ylZ77PQK-595qCc:-NAF0ylZ77PQK-595qCd:b5mhas0) ([raw file](https://github.com/contember/admin/blob/98a7426e971dbdaf5e5bf7dcdf589391089c4b0c/packages/ui/src/components/StyleSheet/Helpers.ts#L51)):*
> ```XML
> const REASONABLE_ARRAY_FLAT_DEPTH = 9
> 
> export function toFlatArrayOfClassNameValues(value: (StyleSheetValueResolver | string | number | boolean | null | undefined)[]): (string | StyleSheetValueResolver)[] {
> ```

can be removed if `toClassNameList` uses `flatMap` and `toStyleSheet` uses `toClassNameList`
___
*[`packages/ui/src/components/StyleSheet/resolveStyleSheet.ts` line 79 at r7](https://reviewable.io/reviews/contember/admin/393#-NAFbZjbBW04rXr1wSs1:-NAFbZjbBW04rXr1wSs2:b-ugphz9) ([raw file](https://github.com/contember/admin/blob/98a7426e971dbdaf5e5bf7dcdf589391089c4b0c/packages/ui/src/components/StyleSheet/resolveStyleSheet.ts#L79)):*
> ```XML
> }
> 
> const UNREPLACED_VARIABLE = /\$[\w_]+/
> ```

`\w` already includes underscore, so just `/\$\w+/` is enough
___
*[`packages/ui/src/components/StyleSheet/resolveStyleSheet.ts` line 85 at r7](https://reviewable.io/reviews/contember/admin/393#-NAFIEecE24jcPrbWWri:-NAFIEecE24jcPrbWWrj:undefined) ([raw file](https://github.com/contember/admin/blob/98a7426e971dbdaf5e5bf7dcdf589391089c4b0c/packages/ui/src/components/StyleSheet/resolveStyleSheet.ts#L85)):*
> ```XML
> }
> 
> function resolveArray(value: (string | StyleSheetValueResolver)[], variables: Record<`$${string}`, StyleSheetVariableValue>): string[] & string {
> ```





_Suggestion:_
```XML
ProcessedClassNameList
```
___
*[`packages/ui/src/components/StyleSheet/resolveStyleSheet.ts` line 85 at r7](https://reviewable.io/reviews/contember/admin/393#-NAFIQCG1Q1XpPMPGpOK:-NAFIQCG1Q1XpPMPGpOL:undefined) ([raw file](https://github.com/contember/admin/blob/98a7426e971dbdaf5e5bf7dcdf589391089c4b0c/packages/ui/src/components/StyleSheet/resolveStyleSheet.ts#L85)):*
> ```XML
> }
> 
> function resolveArray(value: (string | StyleSheetValueResolver)[], variables: Record<`$${string}`, StyleSheetVariableValue>): string[] & string {
> ```





_Suggestion:_
```XML
Record<StyleSheetVariableKey, StyleSheetVariableValue>
```
___
*[`packages/ui/src/components/StyleSheet/resolveStyleSheet.ts` line 85 at r7](https://reviewable.io/reviews/contember/admin/393#-NAFIUWNCSCEUFfYGX3P:-NAFIUWNCSCEUFfYGX3Q:bakui1s) ([raw file](https://github.com/contember/admin/blob/98a7426e971dbdaf5e5bf7dcdf589391089c4b0c/packages/ui/src/components/StyleSheet/resolveStyleSheet.ts#L85)):*
> ```XML
> }
> 
> function resolveArray(value: (string | StyleSheetValueResolver)[], variables: Record<`$${string}`, StyleSheetVariableValue>): string[] & string {
> ```

* the function name is bad
* `string[] & string` is very ugly hack, this needs a different API solution; e.g. add `$$` property with `string` representation or make it the resolved stylesheet callable, so you would either write

~~~tsx
<Stack className={styleSheet.inner.$$} gap={gap} direction={direction}>
~~~

or 

~~~tsx
<Stack className={styleSheet.inner()} gap={gap} direction={direction}>
~~~
___
*[`packages/ui/src/components/StyleSheet/resolveStyleSheet.ts` line 89 at r7](https://reviewable.io/reviews/contember/admin/393#-NAFIjxr0nPtnF41pANM:-NAFIjxr0nPtnF41pANN:b-aa3vvo) ([raw file](https://github.com/contember/admin/blob/98a7426e971dbdaf5e5bf7dcdf589391089c4b0c/packages/ui/src/components/StyleSheet/resolveStyleSheet.ts#L89)):*
> ```XML
>     onlyResolvedEntries(
>       resolveCallableVariablesEntries(
>         variableEntries(
> ```

calling `variableEntries` does nothing because `variable` contains only variable entries
___
*[`packages/ui/src/components/StyleSheet/resolveStyleSheet.ts` line 116 at r7](https://reviewable.io/reviews/contember/admin/393#-NAFGrZc-DS_BnU3OBKO:-NAFGrZc-DS_BnU3OBKP:b-gcp0o0) ([raw file](https://github.com/contember/admin/blob/98a7426e971dbdaf5e5bf7dcdf589391089c4b0c/packages/ui/src/components/StyleSheet/resolveStyleSheet.ts#L116)):*
> ```XML
>   const rootVariables = objectFromEntries(variableEntries(entries))
> 
>   const $ = resolveArray(filterResetClassNames(toClassNameList(merged.$), REMOVE_RESET_CLASS_NAME), rootVariables)
> ```

`merged` is already normalized, so there is no need to normalize it again with `toClassNameList`



_Suggestion:_
```XML
merged.$ ?? []
```
___
*[`packages/ui/src/components/StyleSheet/resolveStyleSheet.ts` line 121 at r7](https://reviewable.io/reviews/contember/admin/393#-NAFfrxx8EAGgZgRWik2:-NAFfrxx8EAGgZgRWik3:b-oy2deh) ([raw file](https://github.com/contember/admin/blob/98a7426e971dbdaf5e5bf7dcdf589391089c4b0c/packages/ui/src/components/StyleSheet/resolveStyleSheet.ts#L121)):*
> ```XML
>     ([key, value]) => {
>       if (value) {
>         value.$ = value.$ !== null
> ```

`value.$` can never be null; only undefined or array
___
*[`packages/ui/src/components/StyleSheet/resolveStyleSheet.ts` line 123 at r7](https://reviewable.io/reviews/contember/admin/393#-NAFfw974o5oqgVpFFOV:-NAFfw974o5oqgVpFFOW:b-peedlq) ([raw file](https://github.com/contember/admin/blob/98a7426e971dbdaf5e5bf7dcdf589391089c4b0c/packages/ui/src/components/StyleSheet/resolveStyleSheet.ts#L123)):*
> ```XML
>         value.$ = value.$ !== null
>           ? resolveArray(
>             toClassNameList(value.$),
> ```

`value.$` is already normalized so calling `toClassNameList` is pointless
___
*[`packages/ui/src/components/StyleSheet/resolveStyleSheet.ts` line 142 at r11](https://reviewable.io/reviews/contember/admin/393#-NAFxk--2eXVh2c0HCWw:-NAFxk--2eXVh2c0HCWx:b-6bzz9m) ([raw file](https://github.com/contember/admin/blob/c5dc6c50ffc728aa6d1d6e8db2a10694f20b7216/packages/ui/src/components/StyleSheet/resolveStyleSheet.ts#L142)):*
> ```XML
> }
> 
> export function useResolveStyleSheet<T extends StyleSheetClassName[]>(...styles: T): [(string[] & string) | undefined, Omit<UnionToIntersection<ToStyleSheet<T[number]>>, '$'>] {
> ```

* maybe rename to just `useStyleSheet`, as this is the only method that is needed inside components
* if multiple parameters are provided, the first should be the always the base stylesheet and the rest should be typechecked against it

sth like


~~~ts
type SubComponentKey = `${Alpha}${string}`
type StyleSheetExtension<Base> =
	| UnprocessedClassNameListItem
	| Array<UnprocessedClassNameListItem>
	| (
		& { $?: UnprocessedClassNameListItem | Array<UnprocessedClassNameListItem> }
		& { [K in keyof Base & StyleSheetVariableKey]?: StyleSheetVariableValue }
		& { [K in keyof Base & SubComponentKey]?: StyleSheetExtension<Base[K]> }
		& StyleSheetVariableMap
	)

type StyleSheetMergeResult<Base, Ext> =
	& { $?: ProcessedClassNameList }
	& { [K in Exclude<keyof Base, keyof Ext> & StyleSheetVariableKey]: Base[K] }
	& { [K in keyof Ext & StyleSheetVariableKey]: Ext[K] }
	& { [K in keyof Base & SubComponentKey]: StyleSheetMergeResult<Base[K], K extends keyof Ext ? Ext[K] : {}> }

export function defineStyleSheet<S extends StyleSheetClassName>(styleSheet: S): ToStyleSheet<S> {
	return toStyleSheet(styleSheet)
}

export function extendStyleSheet<Base, Ext extends StyleSheetExtension<Base>>(base: Base, ext: Ext): StyleSheetM [...]

2022-08-24 20:35 UTC, JanTvrdik requested changes
> *[Reviewable](https://reviewable.io/reviews/contember/admin/393)* status: 3 of 32 files reviewed, 24 unresolved discussions (waiting on @attitude and @JanTvrdik)

___
*[`packages/ui/src/components/Box/Box.tsx` line 82 at r11](https://reviewable.io/reviews/contember/admin/393#-NAGY4g-7U-6brhtSpqu:-NAGY4g-7U-6brhtSpqv:b-nl4y38) ([raw file](https://github.com/contember/admin/blob/c5dc6c50ffc728aa6d1d6e8db2a10694f20b7216/packages/ui/src/components/Box/Box.tsx#L82)):*
> ```XML
> 	$intent: string
> 	$padding: Default | 'no-padding' | 'with-padding'
> }>
> ```

It should not be needed to declare the stylesheet type separately from its default values.

One option would be to do sth like

~~ts
const boxStyleSheet = defineStyleSheet({
	$componentClassName: '$prefix$name',
	$activeClassName: 'is-$active',
	$distinctionClassName: 'view-$distinction',
	$intentClassName: '$intent',
	$paddingClassName: 'view-$padding',

	$active: undefined as boolean | undefined,
	$distinction: undefined as BoxDistinction | undefined,
	$intent: undefined as Intent | undefined,
	$padding: undefined as Default | 'no-padding' | 'with-padding' | undefined,

	$: [
		'$componentClassName',
		'$activeClassName',
		'$distinctionClassName',
		'$intentClassName',
		'$paddingClassName',
	],

	$prefix: 'cui-',
	$name: 'box',
	inner: '$componentClassName-inner',
	header: '$componentClassName-header',
	heading: '$componentClassName-heading',
	actions: '$componentClassName-actions',
})

const extended = extendStyleSheet(boxStyleSheet, {
	$padding: 'no-padding',
	inner: 'my cool type',
})
~~~

or maybe sth like

~~~ts
const boxStyleSheet = defineStyleSheet({
	...

	$active: defineStyleSheetVariable<boolean>,
	$distinction: defineStyleSheetVariable<BoxDistinction>,
	$intent: defineStyleSheetVariable<Intent>,
	$padding: defineStyleSheetVariable<Default | 'no-padding' | 'with-padding'>,
	
	...
})
~~~
___
*[`packages/ui/src/components/StyleSheet/Types.ts` line 48 at r11](https://reviewable.io/reviews/contember/admin/393#-NAGWNeFAWJZLUdwcIZN:-NAGWNeFAWJZLUdwcIZO:bqxyayn) ([raw file](https://github.com/contember/admin/blob/c5dc6c50ffc728aa6d1d6e8db2a10694f20b7216/packages/ui/src/components/StyleSheet/Types.ts#L48)):*
> ```XML
> }
> 
> export type ComponentStyleSheet<S extends StyleSheetClassNameObject = {}> = S & StyleSheetClassNameObject
> ```

this is incorrect, see the `StyleSheetExtension` in other comment 


<!-- Sent from Reviewable.io -->

2023-07-26 20:38 UTC, closed without merging