Add CMS Layout
contember/interface pull request #490
Opened 2023-04-11 11:01 UTC by attitude

2023-04-17 11:42 UTC, matej21 requested changes
> Reviewed 100 of 207 files at r1.
> *[Reviewable](https://reviewable.io/reviews/contember/interface/490)* status: 100 of 207 files reviewed, 21 unresolved discussions (waiting on @attitude)

___
*[`build/api/cms-layout.api.md` line 187 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDqmbX2jPFGtrLRExW:-NTDqmbX2jPFGtrLRExX:be190rh) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/build/api/cms-layout.api.md#L187)):*
> ```Markdown
> export const useLayoutSlotRegistryContext: () => LayoutSlotRegistryContextType;
> 
> // Warnings were encountered during analysis:
> ```

try to solve this warnings
___
*[`ee/cms-layout/package.json` line 35 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDrN5iBpnUXIvM_UMg:-NTDrN5iBpnUXIvM_UMh:b5dt8cs) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/package.json#L35)):*
> ```JSON
> 		"build:js:prod": "vite build --mode production",
> 		"build:css": "vite build --config vite.config.css.js",
> 		"build:license": "cp ../LICENSE ./LICENSE",
> ```

where do you call this command?
___
*[`ee/cms-layout/src/NavigateBackLink.tsx` line 27 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDrhSfBN6WATRgjOtR:-NTDrhSfBN6WATRgjOtS:b-5nkbwi) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/NavigateBackLink.tsx#L27)):*
> ```XML
> 	icon,
> 	ariaLabel = 'Back',
> 	children = 'Back',
> ```

this should be translatable
___
*[`ee/cms-layout/src/tsconfig.json` line 5 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDroLP1k_fuz4p8QTr:-NTDroLP1k_fuz4p8QTs:b3kqx) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/tsconfig.json#L5)):*
> ```jsonc
>   "compilerOptions": {
>     "outDir": "../dist/types",
> 		// TODO: Remove this once PR #488 is merged
> ```

.
___
*[`ee/cms-layout/src/lib/Sidebar.tsx` line 47 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDs67yBsUWUIQPsd9j:-NTDs67yBsUWUIQPsd9k:b-bbrndc) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/lib/Sidebar.tsx#L47)):*
> ```XML
> 		return (
> 			<Layout.Panel
> 				as={as as any}
> ```

why `as any`? maybe we should start writing comments exaplining casts.
___
*[`ee/cms-layout/src/packages/assert-types/AssertionError.ts` line 2 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDspoG-26sDIkrZo_a:-NTDspoG-26sDIkrZo_b:be1fqk6) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/assert-types/AssertionError.ts#L2)):*
> ```XML
> export class AssertionError extends Error {
>   constructor(that: string = 'value to pass assertion', value: unknown) {
> ```

i think value should be first, so you can omit "that"
___
*[`ee/cms-layout/src/packages/assert-types/Parsers.ts` line 5 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDtQ7w1I54VRPL-Zzl:-NTDtQ7w1I54VRPL-Zzm:b4tg5yp) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/assert-types/Parsers.ts#L5)):*
> ```XML
> import { isNonNegativeNumber, isNumber, isString } from './Predicates'
> 
> export function parseString(value: string, name: string = 'value'): string {
> ```

all functions in this file seems unused
___
*[`ee/cms-layout/src/packages/functional/maybe.ts` line 10 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDx4W864eSsv1Az5kl:-NTDx4WBDNrET3FlvsTg:b6r5llr) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/functional/maybe.ts#L10)):*
> ```XML
>  * @returns Result of the then or other function
>  */
> export function maybe<T, U extends T, V, W>(
> ```

I think every usage of this function makes the code less readable.
___
*[`ee/cms-layout/src/packages/functional/nonNegativeNumber.ts` line 8 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDxATt2FpYDZLv6FWF:-NTDxATt2FpYDZLv6FWG:blh9e9p) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/functional/nonNegativeNumber.ts#L8)):*
> ```XML
>  * @returns Input if it is positive, otherwise 0
>  */
> export function nonNegativeNumber(value: number) {
> ```

this should be in assert-types package, right?
___
*[`ee/cms-layout/src/packages/functional/omit.ts` line 1 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDxeKs8VUdum_VultC:-NTDxeKs8VUdum_VultD:b-jmepyd) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/functional/omit.ts#L1)):*
> ```XML
> export function omit<const T extends Object, const K extends keyof T>(object: T, properties: ReadonlyArray<K>): Omit<T, K> {
> ```

unused
___
*[`ee/cms-layout/src/packages/react-context-utilities/createNonNullableContextFactory.ts` line 4 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDyK8r09HmPTq2L7Rl:-NTDyK8r09HmPTq2L7Rm:b-dg3w6m) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-context-utilities/createNonNullableContextFactory.ts#L4)):*
> ```XML
> import { createContext, useContext } from 'react'
> 
> export function createNonNullableContextFactory<T>(displayName: string, initialValue?: T): [Context<T>, () => NonNullable<T>] {
> ```

I like this :100: 
___
*[`ee/cms-layout/src/packages/react-context-utilities/createNullableContextFactory.ts` line 4 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDyZWREkukBB7PCfbN:-NTDyZWREkukBB7PCfbO:b-jmepyd) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-context-utilities/createNullableContextFactory.ts#L4)):*
> ```XML
> import { createContext, useContext } from 'react'
> 
> export function createNullableContextFactory<T>(name: string): [Context<T | null | undefined>, () => T | null | undefined] {
> ```

unused
___
*[`ee/cms-layout/src/packages/react-hooks/maybeRef.ts` line 10 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDydNB-lcQlHJN6Z5J:-NTDydNB-lcQlHJN6Z5K:bynieu6) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-hooks/maybeRef.ts#L10)):*
> ```XML
>  * @returns Unwrapped value
>  */
> export function maybeRef<T>(value: RefObjectOrElement<T>): T | null {
> ```

maybe call it sth like unwrapRefValue?
___
*[`ee/cms-layout/src/packages/react-hooks/useCache.ts` line 4 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDz3pN3WhToR6Sze1-:-NTDz3pN3WhToR6Sze10:b-rxo1az) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-hooks/useCache.ts#L4)):*
> ```XML
> import { assert, isTrue } from '../assert-types'
> 
> export function useCache() {
> ```

why don't you use useMemo?
___
*[`ee/cms-layout/src/packages/react-hooks/useElementSize.ts` line 33 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDzLwn6ghZZ6DQWZZ5:-NTDzLwn6ghZZ6DQWZZ6:bxwa5t7) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-hooks/useElementSize.ts#L33)):*
> ```XML
> 	const getSizeFromResizeObserverEntry = useMemo(() => getSizeFromResizeObserverEntryFactory(box), [box])
> 
> 	const [width, setWidth] = useState<number | undefined>(maybe(maybeRef(refOrElement), isNotNullish, getElementWidth, undefined))
> ```

```
	const refValue = maybeRef(refOrElement)
	const [width, setWidth] = useState<number | undefined>(refValue?.offsetWidth)
	const [height, setHeight] = useState<number | undefined>(ref [...]

2023-04-17 13:29 UTC, attitude reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/contember/interface/490#-:-NTEFKFK4pC1HdZgObiN:bnfp4nl)* status: 0 of 212 files reviewed, 20 unresolved discussions (waiting on @attitude and @matej21)

___
*[`build/api/cms-layout.api.md` line 187 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDqmbX2jPFGtrLRExW:-NTEFFeD1v7h_vRPUzWE:b-xncabl) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/build/api/cms-layout.api.md#L187)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

try to solve this warnings
</blockquote></details>

OK. Exported all necessary types.
___
*[`ee/cms-layout/package.json` line 35 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDrN5iBpnUXIvM_UMg:-NTEFBZJE1uwQkW92No5:b-bnx9jc) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/package.json#L35)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

where do you call this command?
</blockquote></details>

OK. Fixed, calling in `yarn build`
___
*[`ee/cms-layout/src/NavigateBackLink.tsx` line 27 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDrhSfBN6WATRgjOtR:-NTEExktAiOYqftHRak4:b-aeccei) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/NavigateBackLink.tsx#L27)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

this should be translatable
</blockquote></details>

I think this should be client-code responsibility to pass translated string.
___
*[`ee/cms-layout/src/tsconfig.json` line 5 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDroLP1k_fuz4p8QTr:-NTEEv6V4CLj8oReJfw5:b-yzvsqb) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/tsconfig.json#L5)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

.
</blockquote></details>

OK. Removed
___
*[`ee/cms-layout/src/lib/Sidebar.tsx` line 47 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDs67yBsUWUIQPsd9j:-NTEEp_T5Sx1Sw0dadeq:b-lwoa9q) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/lib/Sidebar.tsx#L47)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

why `as any`? maybe we should start writing comments exaplining casts.
</blockquote></details>

OK. Comment added.
___
*[`ee/cms-layout/src/packages/assert-types/AssertionError.ts` line 2 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDspoG-26sDIkrZo_a:-NTEEB8D5rc9VflFaLD9:byfryg0) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/assert-types/AssertionError.ts#L2)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

i think value should be first, so you can omit "that"
</blockquote></details>

OK. Changing order.
___
*[`ee/cms-layout/src/packages/functional/maybe.ts` line 10 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDx4W864eSsv1Az5kl:-NTEC3oF38nW3DvxnPyf:b13c570) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/functional/maybe.ts#L10)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

I think every usage of this function makes the code less readable.
</blockquote></details>

This allows to set e.g. initial value of `setState()` base on more complex condition than a null coalescing operator. Alternative ternary condition would be less readable in the same way.
___
*[`ee/cms-layout/src/packages/functional/omit.ts` line 1 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDxeKs8VUdum_VultC:-NTEArlF-lBH0KOU4c9V:b-npgpux) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/functional/omit.ts#L1)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

unused
</blockquote></details>

It is a util. I don't want to write types again a week later when needed.
___
*[`ee/cms-layout/src/packages/react-context-utilities/createNullableContextFactory.ts` line 4 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDyZWREkukBB7PCfbN:-NTEAd-f1N6wAk0Ei_a3:bbm4r7v) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-context-utilities/createNullableContextFactory.ts#L4)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

unused
</blockquote></details>

But useful to have pair function with `createNonNullable...`.
___
*[`ee/cms-layout/src/packages/react-hooks/maybeRef.ts` line 10 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDydNB-lcQlHJN6Z5J:-NTEA_GJ6nSDKxVAa-8z:bay8hwk) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-hooks/maybeRef.ts#L10)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

maybe call it sth like unwrapRefValue?
</blockquote></details>

You don't like naming?
___
*[`ee/cms-layout/src/packages/react-hooks/useCache.ts` line 4 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDz3pN3WhToR6Sze1-:-NTEAWaU4pGA4GOSRfgZ:b-ywlg9z) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-hooks/useCache.ts#L4)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

why don't you use useMemo?
</blockquote></details>

Cannot call useMemo inside a consumer callback.
___
*[`ee/cms-layout/src/packages/react-hooks/useElementSize.ts` line 33 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDzLwn6ghZZ6DQWZZ5:-NTEAJbgB0ZTJ4snSKy5:bp4xg0f) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-hooks/useElementSize.ts#L33)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

```
	const refValue = maybeRef(refOrElement)
	const [width, setWidth] = useState<number | undefined>(refValue?.offsetWidth)
	const [height, setHeight] = useState<number | undefined>(refValue?.offsetHeight)
```
is much more readable
</blockquote></details>

This will give different result, e.g. will not call `getElementWidth`.
___
*[`ee/cms-layout/src/packages/react-hooks/useExpectSameValueReference.ts` line 4 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDzwUXARqJ93YJzRb3:-NTEKf1340RvZuXg_DUp:bg6db11) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-hooks/useExpectSameValueReference.ts#L4)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

see useConstantValueInvariant in react-utils
</blockquote></details>

useConstantValueInvariant throws always throws, no option to warn-only and works only in dev. Implementations are IMO for different use-cases.

As a side note, I personally would expect `useConstantValueInvariant` to always throw, even in production code.
___
*[`ee/cms-layout/src/packages/ui-directives/Context.tsx` line 23 at r1](https://reviewable.io/reviews/contember/interface/490#-NTE0E227Se7GR3z17Hd:-NTEG_WM46mmuQKGYovO:bpijtz7) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/ui-directives/Context.tsx#L23)) [...]

2023-04-17 15:23 UTC, matej21 requested changes
> Reviewed 30 of 212 files at r2, 168 of 169 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 3 of 4 files at r6, 21 of 22 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/interface/490)* status: all files reviewed, 14 unresolved discussions (waiting on @attitude)

___
*[`ee/cms-layout/src/packages/ui-focus-scope/FocusScope.tsx` line 64 at r8](https://reviewable.io/reviews/contember/interface/490#-NTElEdT8JThzSO2DPaV:-NTElEdT8JThzSO2DPaW:bld9il7) ([raw file](https://github.com/contember/interface/blob/cbc95a8ae0e4aa970b48c73ce262727baf3cc0dd/ee/cms-layout/src/packages/ui-focus-scope/FocusScope.tsx#L64)):*
> ```XML
> }
> 
> export function FocusScope({ active = true, children, pressToSkipToLastLabel = 'Skip to last focusable element', pressToSkipToFirstLabel = 'Skip to first focusable element' }: FocusScopeProps) {
> ```

should be translatable. now, it is not possible to change the text within the cms layout
___
*[`ee/cms-layout/src/packages/ui-insets/Helpers.ts` line 31 at r8](https://reviewable.io/reviews/contember/interface/490#-NTElLB18qqhbzxe0_ke:-NTElLB18qqhbzxe0_kf:blpba49) ([raw file](https://github.com/contember/interface/blob/cbc95a8ae0e4aa970b48c73ce262727baf3cc0dd/ee/cms-layout/src/packages/ui-insets/Helpers.ts#L31)):*
> ```XML
> function clampElementInsets(containerInsets: ContainerInsets | null | undefined, elementInsets: ContainerInsets): ContainerInsets {
> 	return {
> 		bottom: maybe(containerInsets?.bottom, isNonNegativeNumber, bottom => elementInsets.bottom > bottom ? bottom : elementInsets.bottom, 0),
> ```

pls rewrite as we discussed
___
*[`ee/cms-layout/src/packages/ui-layout/LayoutRoot.tsx` line 41 at r8](https://reviewable.io/reviews/contember/interface/490#-NTEm8fc58OeH7ijkfEp:-NTEm8fc58OeH7ijkfEq:b3kqx) ([raw file](https://github.com/contember/interface/blob/cbc95a8ae0e4aa970b48c73ce262727baf3cc0dd/ee/cms-layout/src/packages/ui-layout/LayoutRoot.tsx#L41)):*
> ```XML
> 								))}
> 								{...rest}
> 								style={stylesCache(() => getPanelsCSSCustomProperties(panels, width, rest.style), [panels, rest.style, width])}
> ```

.
___
*[`ee/cms-layout/src/packages/ui-layout-slots/LayoutSlotPortal.tsx` line 13 at r8](https://reviewable.io/reviews/contember/interface/490#-NTEmx1y-lvpKhZ_eQeE:-NTEmx1y-lvpKhZ_eQeF:b9299em) ([raw file](https://github.com/contember/interface/blob/cbc95a8ae0e4aa970b48c73ce262727baf3cc0dd/ee/cms-layout/src/packages/ui-layout-slots/LayoutSlotPortal.tsx#L13)):*
> ```XML
> 	} = useRenderToSlotPortalContext()
> 
> 	const instanceId = useRef(Math.random().toString(36).substring(2, 9))
> ```

maybe wrap the default value into useMemo to avoid re-computation on each redraw?
___
*[`ee/cms-layout/src/packages/ui-responsive-app-layout/ResponsiveAppLayout.tsx` line 40 at r8](https://reviewable.io/reviews/contember/interface/490#-NTEnP-58FdrW0b0GNgP:-NTEnP-58FdrW0b0GNgQ:b9xukrm) ([raw file](https://github.com/contember/interface/blob/cbc95a8ae0e4aa970b48c73ce262727baf3cc0dd/ee/cms-layout/src/packages/ui-responsive-app-layout/ResponsiveAppLayout.tsx#L40)):*
> ```XML
> 		const footerSize = useElementSize(layoutFooterRef)
> 
> 		const headerHeight = (headerSize.height ?? 0) * (headerSize.width ?? 0) === 0 ? undefined : headerSize.height
> ```

isn't this same as `!headerSize.height || !headerSize.width`?


<!-- Sent from Reviewable.io -->

2023-04-17 19:49 UTC, attitude reviewed
> *[Reviewable](https://reviewable.io/reviews/contember/interface/490)* status: 170 of 212 files reviewed, 14 unresolved discussions (waiting on @matej21)

___
*[`ee/cms-layout/src/NavigateBackLink.tsx` line 27 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDrhSfBN6WATRgjOtR:-NTFgAPt796M9UbFC81r:b8orowd) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/NavigateBackLink.tsx#L27)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

we use useMessageFormatter where possible
</blockquote></details>

Done. Added `useMessageFormatter`
___
*[`ee/cms-layout/src/packages/react-hooks/useElementSize.ts` line 33 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDzLwn6ghZZ6DQWZZ5:-NTFMLFX6D9yruVfAFqg:b-896fix) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-hooks/useElementSize.ts#L33)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

getElementWidth just fetches offetWidth prop
</blockquote></details>

Done.
___
*[`ee/cms-layout/src/packages/react-hooks/useExpectSameValueReference.ts` line 4 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDzwUXARqJ93YJzRb3:-NTFPS0mAjLO7fZkQSZc:b-l5f39f) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-hooks/useExpectSameValueReference.ts#L4)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

i see that this uses deepEqual.. ok.. but we should maybe unify that error behaviour someday..
</blockquote></details>

Done. Added a TODO comment
___
*[`ee/cms-layout/src/packages/ui-directives/Context.tsx` line 23 at r1](https://reviewable.io/reviews/contember/interface/490#-NTE0E227Se7GR3z17Hd:-NTFP_5F5ldIblWvDIOc:b-896fix) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/ui-directives/Context.tsx#L23)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

at first, I thought, you are using global console object. so add some prefix e.g. consoleLogger, innerConsole or sth like this
</blockquote></details>

Done.
___
*[`ee/cms-layout/src/packages/ui-focus-scope/FocusScope.tsx` line 64 at r8](https://reviewable.io/reviews/contember/interface/490#-NTElEdT8JThzSO2DPaV:-NTFgG5u5Hkf2OqgmP9M:b-vsqhib) ([raw file](https://github.com/contember/interface/blob/cbc95a8ae0e4aa970b48c73ce262727baf3cc0dd/ee/cms-layout/src/packages/ui-focus-scope/FocusScope.tsx#L64)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

should be translatable. now, it is not possible to change the text within the cms layout
</blockquote></details>

Done. Added `useMessageFormatter`
___
*[`ee/cms-layout/src/packages/ui-insets/Helpers.ts` line 31 at r8](https://reviewable.io/reviews/contember/interface/490#-NTElLB18qqhbzxe0_ke:-NTFPnsn0opk4WzVBGPO:b-896fix) ([raw file](https://github.com/contember/interface/blob/cbc95a8ae0e4aa970b48c73ce262727baf3cc0dd/ee/cms-layout/src/packages/ui-insets/Helpers.ts#L31)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

pls rewrite as we discussed
</blockquote></details>

Done.
___
*[`ee/cms-layout/src/packages/ui-layout/LayoutRoot.tsx` line 41 at r8](https://reviewable.io/reviews/contember/interface/490#-NTEm8fc58OeH7ijkfEp:-NTFPtFG3cHd5wU5-wrO:b-896fix) ([raw file](https://github.com/contember/interface/blob/cbc95a8ae0e4aa970b48c73ce262727baf3cc0dd/ee/cms-layout/src/packages/ui-layout/LayoutRoot.tsx#L41)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`ee/cms-layout/src/packages/ui-layout-slots/LayoutSlotPortal.tsx` line 13 at r8](https://reviewable.io/reviews/contember/interface/490#-NTEmx1y-lvpKhZ_eQeE:-NTFUkRkAPdWmQsvpMe5:b-896fix) ([raw file](https://github.com/contember/interface/blob/cbc95a8ae0e4aa970b48c73ce262727baf3cc0dd/ee/cms-layout/src/packages/ui-layout-slots/LayoutSlotPortal.tsx#L13)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

maybe wrap the default value into useMemo to avoid re-computation on each redraw?
</blockquote></details>

Done.
___
*[`ee/cms-layout/src/packages/ui-responsive-app-layout/ResponsiveAppLayout.tsx` line 40 at r8](https://reviewable.io/reviews/contember/interface/490#-NTEnP-58FdrW0b0GNgP:-NTFZNXl7GXPfUWSY0yl:b6w6x48) ([raw file](https://github.com/contember/interface/blob/cbc95a8ae0e4aa970b48c73ce262727baf3cc0dd/ee/cms-layout/src/packages/ui-responsive-app-layout/ResponsiveAppLayout.tsx#L40)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

isn't this same as `!headerSize.height || !headerSize.width`?
</blockquote></details>

Done. You are right. 



_Code quote:_
```XML
const headerHeight = (headerSize.height ?? 0) * (headerSize.width ?? 0) === 0 ? undefined : headerSize.height
```
___
*[`ee/cms-layout/src/packages/functional/maybe.ts` line 10 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDx4W864eSsv1Az5kl:-NTFZUkH0kW47hwVeiCU:b-896fix) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/functional/maybe.ts#L10)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

you can always create a function for that
</blockquote></details>

Done.
___
*[`ee/cms-layout/src/packages/functional/omit.ts` line 1 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDxeKs8VUdum_VultC:-NTFAB370oCRWkYdoBUM:b-wnfmk9) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/functional/omit.ts#L1)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

just a code to maintain..
</blockquote></details>

Done. Removed.
___
*[`ee/cms-layout/src/packages/react-context-utilities/createNullableContextFactory.ts` line 4 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDyZWREkukBB7PCfbN:-NTFAXo_78t1yttQEjPQ:b-wnfmk9) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-context-utilities/createNullableContextFactory.ts#L4)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

just a code you need to maintain. its easy to create such function when someone actually needs it.
</blockquote></details>

Done. Removed.
___
*[`ee/cms-layout/src/packages/react-hooks/useCache.ts` line 4 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDz3pN3WhToR6Sze1-:-NTFFOUY4wXW0FpIn43D:b-896fix) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-hooks/useCache.ts#L4)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

so why don't you extract the consumer children into a component?
</blockquote></details>

Done.
___
*[`ee/cms-layout/src/packages/react-hooks/maybeRef.ts` line 10 at r1](https://reviewable.io/reviews/contember/interface/490#-NTDydNB-lcQlHJN6Z5J:-NTFArPs6E-gHB5FNV7H:bjpyuvk) ([raw file](https://github.com/contember/interface/blob/d2c5d92db55bf35f46831db18dbaa53091acb88d/ee/cms-layout/src/packages/react-hooks/maybeRef.ts#L10)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

yep
</blockquote></details>

Done. Renamed to `unwrapRefValue()`


<!-- Sent from Reviewable.io -->

2023-04-18 09:16 UTC, matej21 approved these changes
> Reviewed 42 of 42 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/interface/490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @attitude)



<!-- Sent from Reviewable.io -->

2023-04-18 10:40 UTC, merged